name: release
on:
  push:
    tags:
      - v*.*.*
env:
  # THIS GITHUB_TOKEN IS A REQUIREMENT TO BE ABLE TO WRITE TO GH RELEASES
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # IF YOU NEED TO PUBLISH A NPM PACKAGE THEN ENSURE A NPM_TOKEN SECRET IS SET
  NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}

  # IF YOU NEED TO PUBLISH A NUGET PACKAGE THEN ENSURE AN NUGET_PUBLISH_KEY
  # SECRET IS SET
  # NUGET_PUBLISH_KEY: ${{ YOUR NUGET PUBLISH KEY HERE }}

  # IF YOU NEED TO PUBLISH A PYPI PACKAGE SET CHANGE PYPI_PASSWORD, PYPI_USERNAME TO YOUR CREDENTIALS.
  PYPI_PASSWORD: __token__
  PYPI_USERNAME: ${{ secrets.PYPI_DEPLOY_TOKEN }}
jobs:
  prerequisites:
    name: prerequisites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.goversion}}
    strategy:
      fail-fast: true
      matrix:
        goversion:
          - 1.20.x
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.goversion}}
      - name: Build tfgen & provider binaries
        run: make provider
      - name: Tar provider binaries
        run: tar -zcf ${{ github.workspace }}/bin/provider.tar.gz -C ${{
          github.workspace }}/bin/ pulumi-resource-${{ env.PROVIDER }}
          pulumi-tfgen-${{ env.PROVIDER }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Set PreRelease Version
        run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: -p 3 release --clean
          version: latest
    strategy:
      fail-fast: true
      matrix:
        goversion:
          - 1.20.x
  build_sdk:
    name: Build SDKs
    runs-on: ubuntu-latest
    needs: prerequisites
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Download provider + tfgen binaries
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PROVIDER }}-provider.tar.gz
          path: ${{ github.workspace }}/bin
      - name: Untar provider binaries
        run: >-
          tar -zxf ${{ github.workspace }}/bin/provider.tar.gz -C ${{
          github.workspace}}/bin

          find ${{ github.workspace }} -name "pulumi-*-${{ env.PROVIDER }}" -print -exec chmod +x {} \;
      - name: Build SDK
        run: make build_${{ matrix.language }}
      - name: Compress SDK folder
        run: tar -zcf sdk/${{ matrix.language }}.tar.gz -C sdk/${{ matrix.language }} .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.language  }}-sdk.tar.gz
          path: ${{ github.workspace}}/sdk/${{ matrix.language }}.tar.gz
    strategy:
      fail-fast: true
      matrix:
        language:
          - nodejs
          - go
  publish_sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    needs: build_sdk
    steps:
      - name: Publish SDKs
        uses: pulumi/pulumi-package-publisher@v0.0.13
        with:
          sdk: nodejs
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
          - 3.1.301
        goversion:
          - 1.18.x
        nodeversion:
          - 20.x
        pythonversion:
          - "3.9"
